### ISSUE TITLE
Validation failure with default billing address and Mollie credit card selected

### ISSUE THREAD

**Issue by avstudnitz** [mollie/magento2-hyva-checkout#30] opened 2024-10-23 10:40 UTC
When clicking "Place Order", it doesn't submit the order, but instead scrolls up to the address selection.

### Prerequisites

* Mollie Creditcard is selected 
* Customer logged in, having a default billing address
* The initial address isn't changed
* Virtual order (might not be a prerequisite, haven't tested otherwise)
* Onepage layout (might not be a prerequisite, haven't tested otherwise)

### Additional notes

* It works for prepayment and Mollie Paypal. This is independent of which payment method was preselected or selected before.
* it works after I selected another address. It doesn't seem to depend on the address itself, it's only important that it hasn't been changed. It also works if I select another address and then the initial address again.
* It could have to do with the frontend validation. 
* No messages in the JS console or in the log files.
* The last AJAX call goes out to `/magewire/post/livewire/message/checkout.payment.method.mollie_methods_creditcard`, executing the `setCardToken` method. It returns successfully. After that, the window scrolls up. The call seems to be executed in the vendor/mollie/magento2-hyva-checkout/src/Mollie_HyvaCheckout/view/frontend/templates/component/payment/method/creditcard.phtml file.
* If I disable the lines https://github.com/mollie/magento2-hyva-checkout/blob/main/src/Mollie_HyvaCheckout/view/frontend/templates/component/payment/method/creditcard.phtml#L48-L64, it works. But, as the token isn't set, mollie shows me a form where I can enter my CC number instead of using the number I entered in the checkout.
* I also tested switching to the default theme and removing all customization for the checkout - no change.

**Comment by Frank-Magmodules** [comment] 2024-10-24 17:48
Hi There @avstudnitz , 

We’re actively working on this issue, but it could also be related to the Hyvä checkout itself or Magewire. We’re investigating this together with the Hyvä team and will get back to you shortly.

**Comment by avstudnitz** [comment] 2024-10-29 11:36
I just double-checked on https://checkout-demo.hyva.io/ - same effect, you cannot checkout in that case. 

![grafik](https://github.com/user-attachments/assets/08bd7375-21b8-4894-90eb-a1c9252aac89)

**Comment by avstudnitz** [comment] 2024-10-29 13:31
Pull Request tested positively on my local machine 👍

**Comment by Frank-Magmodules** [comment] 2024-10-29 13:33
Thank you so much, @avstudnitz, for confirming that! That’s great, and the release is now publicly available! I appreciate you opening this issue with all the right information and your patience. Since it’s confirmed as working, I’ll go ahead and close this issue for now. Feel free to comment or reopen it anytime if needed.

**Closed by Frank-Magmodules** 2024-10-29 13:33 UTC
Labels: Investigating
